"""remove car_type_id from cars

Revision ID: 6294cbc48afc
Revises: 5e31ab41b52a
Create Date: 2026-04-30 23:13:43.349209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6294cbc48afc'
down_revision: Union[str, Sequence[str], None] = '5e31ab41b52a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('cars', schema=None) as batch_op:
        # On supprime juste la colonne (SQLite recrée la table sans la FK)
        batch_op.drop_column('car_type_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_type_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'car_types', ['car_type_id'], ['id'])

    # ### end Alembic commands ###
